[project]
name = "builtintools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=0.2.0",
    "litellm>=1.67.0",
    "python-dotenv>=1.1.0",
]
